sudo: false
language: python
cache: pip
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -U pip setuptools
  - pip install tox-travis
  - pip install codecov
script:
  - tox
after_success:
  - codecov
