sudo: false
language: python
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -U pip setuptools
  - pip install tox-travis pre-commit
  - pip install codecov
  - pip install readme_renderer
script:
  - tox
  - pre-commit run --all-files
  - python setup.py check -r -s
after_success:
  - codecov
